apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus               
    type: prometheus
    access: proxy
    url: http://192.168.71.180:9080      # Prometheus on Core's core_net
    isDefault: true
    editable: true