{
 "title": "KPI measurements",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CU-UP Backhaul Volume (per CU-UP)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "rawQueryText": "SELECT tstamp AS \"time\",\n       CASE WHEN ran_ue_id = 2 THEN 'cuup_e (URLLC)' ELSE 'cuup_co (eMBB+mIoT)' END AS metric,\n       SUM(measure_value) AS value\nFROM KPM_MeasRecord\nWHERE meas_name = 'DRB.PdcpSduVolumeDL' AND ran_ue_id IS NOT NULL\n AND tstamp BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nGROUP BY tstamp, metric\nORDER BY tstamp",
     "queryText": "SELECT tstamp AS \"time\",\n       CASE WHEN ran_ue_id = 2 THEN 'cuup_e (URLLC)' ELSE 'cuup_co (eMBB+mIoT)' END AS metric,\n       SUM(measure_value) AS value\nFROM KPM_MeasRecord\nWHERE meas_name = 'DRB.PdcpSduVolumeDL' AND ran_ue_id IS NOT NULL\n AND tstamp BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nGROUP BY tstamp, metric\nORDER BY tstamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  { "title": "E2SM-KPM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CARR.PDSCHMCSDist (MCS table = 1)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT\n  binZ AS \"MCS\",\n  MAX(CASE WHEN binX = 1 THEN measure_value END) AS \"RI 1\",\n  MAX(CASE WHEN binX = 2 THEN measure_value END) AS \"RI 2\",\n  MAX(CASE WHEN binX = 3 THEN measure_value END) AS \"RI 3\",\n  MAX(CASE WHEN binX = 4 THEN measure_value END) AS \"RI 4\",\n  MAX(CASE WHEN binX = 5 THEN measure_value END) AS \"RI 5\",\n  MAX(CASE WHEN binX = 6 THEN measure_value END) AS \"RI 6\",\n  MAX(CASE WHEN binX = 7 THEN measure_value END) AS \"RI 7\",\n  MAX(CASE WHEN binX = 8 THEN measure_value END) AS \"RI 8\"\nFROM\n  KPM_MeasRecord\nWHERE\n  meas_name = 'CARR.PDSCHMCSDist' AND\n  binY = 1 AND -- Filtering for MCS Table 1\n  tstamp = (SELECT MAX(tstamp) FROM KPM_MeasRecord WHERE meas_name = 'CARR.PDSCHMCSDist')\nGROUP BY\n  binZ\nORDER BY\n  binZ",
     "rawQueryText": "SELECT\n  binZ AS \"MCS\",\n  MAX(CASE WHEN binX = 1 THEN measure_value END) AS \"RI 1\",\n  MAX(CASE WHEN binX = 2 THEN measure_value END) AS \"RI 2\",\n  MAX(CASE WHEN binX = 3 THEN measure_value END) AS \"RI 3\",\n  MAX(CASE WHEN binX = 4 THEN measure_value END) AS \"RI 4\",\n  MAX(CASE WHEN binX = 5 THEN measure_value END) AS \"RI 5\",\n  MAX(CASE WHEN binX = 6 THEN measure_value END) AS \"RI 6\",\n  MAX(CASE WHEN binX = 7 THEN measure_value END) AS \"RI 7\",\n  MAX(CASE WHEN binX = 8 THEN measure_value END) AS \"RI 8\"\nFROM\n  KPM_MeasRecord\nWHERE\n  meas_name = 'CARR.PDSCHMCSDist' AND\n  binY = 1 AND -- Filtering for MCS Table 1\n  tstamp = (SELECT MAX(tstamp) FROM KPM_MeasRecord WHERE meas_name = 'CARR.PDSCHMCSDist')\nGROUP BY\n  binZ\nORDER BY\n  binZ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "CARR.PDSCHMCSDist (MCS table = 2)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT\n  binZ AS \"MCS\",\n  MAX(CASE WHEN binX = 1 THEN measure_value END) AS \"RI 1\",\n  MAX(CASE WHEN binX = 2 THEN measure_value END) AS \"RI 2\",\n  MAX(CASE WHEN binX = 3 THEN measure_value END) AS \"RI 3\",\n  MAX(CASE WHEN binX = 4 THEN measure_value END) AS \"RI 4\",\n  MAX(CASE WHEN binX = 5 THEN measure_value END) AS \"RI 5\",\n  MAX(CASE WHEN binX = 6 THEN measure_value END) AS \"RI 6\",\n  MAX(CASE WHEN binX = 7 THEN measure_value END) AS \"RI 7\",\n  MAX(CASE WHEN binX = 8 THEN measure_value END) AS \"RI 8\"\nFROM\n  KPM_MeasRecord\nWHERE\n  meas_name = 'CARR.PDSCHMCSDist' AND\n  binY = 2 AND -- Filtering for MCS Table 2\n  tstamp = (SELECT MAX(tstamp) FROM KPM_MeasRecord WHERE meas_name = 'CARR.PDSCHMCSDist')\nGROUP BY\n  binZ\nORDER BY\n  binZ",
     "rawQueryText": "SELECT\n  binZ AS \"MCS\",\n  MAX(CASE WHEN binX = 1 THEN measure_value END) AS \"RI 1\",\n  MAX(CASE WHEN binX = 2 THEN measure_value END) AS \"RI 2\",\n  MAX(CASE WHEN binX = 3 THEN measure_value END) AS \"RI 3\",\n  MAX(CASE WHEN binX = 4 THEN measure_value END) AS \"RI 4\",\n  MAX(CASE WHEN binX = 5 THEN measure_value END) AS \"RI 5\",\n  MAX(CASE WHEN binX = 6 THEN measure_value END) AS \"RI 6\",\n  MAX(CASE WHEN binX = 7 THEN measure_value END) AS \"RI 7\",\n  MAX(CASE WHEN binX = 8 THEN measure_value END) AS \"RI 8\"\nFROM\n  KPM_MeasRecord\nWHERE\n  meas_name = 'CARR.PDSCHMCSDist' AND\n  binY = 2 AND -- Filtering for MCS Table 2\n  tstamp = (SELECT MAX(tstamp) FROM KPM_MeasRecord WHERE meas_name = 'CARR.PDSCHMCSDist')\nGROUP BY\n  binZ\nORDER BY\n  binZ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "CARR.PDSCHMCSDist (MCS table = 3)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "queryText": "SELECT\n  binZ AS \"MCS\",\n  MAX(CASE WHEN binX = 1 THEN measure_value END) AS \"RI 1\",\n  MAX(CASE WHEN binX = 2 THEN measure_value END) AS \"RI 2\",\n  MAX(CASE WHEN binX = 3 THEN measure_value END) AS \"RI 3\",\n  MAX(CASE WHEN binX = 4 THEN measure_value END) AS \"RI 4\",\n  MAX(CASE WHEN binX = 5 THEN measure_value END) AS \"RI 5\",\n  MAX(CASE WHEN binX = 6 THEN measure_value END) AS \"RI 6\",\n  MAX(CASE WHEN binX = 7 THEN measure_value END) AS \"RI 7\",\n  MAX(CASE WHEN binX = 8 THEN measure_value END) AS \"RI 8\"\nFROM\n  KPM_MeasRecord\nWHERE\n  meas_name = 'CARR.PDSCHMCSDist' AND\n  binY = 3 AND -- Filtering for MCS Table 3\n  tstamp = (SELECT MAX(tstamp) FROM KPM_MeasRecord WHERE meas_name = 'CARR.PDSCHMCSDist')\nGROUP BY\n  binZ\nORDER BY\n  binZ",
     "rawQueryText": "SELECT\n  binZ AS \"MCS\",\n  MAX(CASE WHEN binX = 1 THEN measure_value END) AS \"RI 1\",\n  MAX(CASE WHEN binX = 2 THEN measure_value END) AS \"RI 2\",\n  MAX(CASE WHEN binX = 3 THEN measure_value END) AS \"RI 3\",\n  MAX(CASE WHEN binX = 4 THEN measure_value END) AS \"RI 4\",\n  MAX(CASE WHEN binX = 5 THEN measure_value END) AS \"RI 5\",\n  MAX(CASE WHEN binX = 6 THEN measure_value END) AS \"RI 6\",\n  MAX(CASE WHEN binX = 7 THEN measure_value END) AS \"RI 7\",\n  MAX(CASE WHEN binX = 8 THEN measure_value END) AS \"RI 8\"\nFROM\n  KPM_MeasRecord\nWHERE\n  meas_name = 'CARR.PDSCHMCSDist' AND\n  binY = 3 AND -- Filtering for MCS Table 3\n  tstamp = (SELECT MAX(tstamp) FROM KPM_MeasRecord WHERE meas_name = 'CARR.PDSCHMCSDist')\nGROUP BY\n  binZ\nORDER BY\n  binZ",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "DRB.PdcpSduVolumeDL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "queryText": "SELECT\n    tstamp AS \"time\",\n    'UE ' || ran_ue_id AS metric,\n    AVG(measure_value) AS value\nFROM KPM_MeasRecord\nWHERE meas_name = 'DRB.PdcpSduVolumeDL' AND ran_ue_id IS NOT NULL\n AND tstamp BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nGROUP BY tstamp, ran_ue_id\nORDER BY tstamp",
     "rawQueryText": "SELECT\n    tstamp AS \"time\",\n    'UE ' || ran_ue_id AS metric,\n    AVG(measure_value) AS value\nFROM KPM_MeasRecord\nWHERE meas_name = 'DRB.PdcpSduVolumeDL' AND ran_ue_id IS NOT NULL\n AND tstamp BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nGROUP BY tstamp, ran_ue_id\nORDER BY tstamp",
     "unit": "Mbits",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "DRB.PdcpSduVolumeUL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "queryText": "SELECT\n    tstamp AS \"time\",\n    'UE ' || ran_ue_id AS metric,\n    AVG(measure_value) AS value\nFROM KPM_MeasRecord\nWHERE meas_name = 'DRB.PdcpSduVolumeUL' AND ran_ue_id IS NOT NULL\n AND tstamp BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nGROUP BY tstamp, ran_ue_id\nORDER BY tstamp",
     "rawQueryText": "SELECT\n    tstamp AS \"time\",\n    'UE ' || ran_ue_id AS metric,\n    AVG(measure_value) AS value\nFROM KPM_MeasRecord\nWHERE meas_name = 'DRB.PdcpSduVolumeUL' AND ran_ue_id IS NOT NULL\n AND tstamp BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nGROUP BY tstamp, ran_ue_id\nORDER BY tstamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "DRB.UEThpDl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Mbits/s" } },
   "targets": [
    {
     "queryText": "SELECT\n    tstamp AS \"time\",\n    'UE ' || ran_ue_id AS metric,\n    AVG(measure_value)/1000000 AS value\nFROM KPM_MeasRecord\nWHERE meas_name = 'DRB.UEThpDl' AND ran_ue_id IS NOT NULL\n AND tstamp BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nGROUP BY tstamp, ran_ue_id\nORDER BY tstamp",
     "rawQueryText": "SELECT\n    tstamp AS \"time\",\n    'UE ' || ran_ue_id AS metric,\n    AVG(measure_value)/1000000 AS value\nFROM KPM_MeasRecord\nWHERE meas_name = 'DRB.UEThpDl' AND ran_ue_id IS NOT NULL\n AND tstamp BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nGROUP BY tstamp, ran_ue_id\nORDER BY tstamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "DRB.UEThpUl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Mbits/s" } },
   "targets": [
    {
     "queryText": "SELECT\n    tstamp AS \"time\",\n    'UE ' || ran_ue_id AS metric,\n    AVG(measure_value)/1000000 AS value\nFROM KPM_MeasRecord\nWHERE meas_name = 'DRB.UEThpUl' AND ran_ue_id IS NOT NULL\n AND tstamp BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\n GROUP BY tstamp, ran_ue_id\nORDER BY tstamp",
     "rawQueryText": "SELECT\n    tstamp AS \"time\",\n    'UE ' || ran_ue_id AS metric,\n    AVG(measure_value)/1000000 AS value\nFROM KPM_MeasRecord\nWHERE meas_name = 'DRB.UEThpUl' AND ran_ue_id IS NOT NULL\n AND tstamp BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nGROUP BY tstamp, ran_ue_id\nORDER BY tstamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "RRU.PrbTotDl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT\n   tstamp AS \"time\",\n   'UE ' || ran_ue_id AS metric,\n   AVG(measure_value) AS value\nFROM KPM_MeasRecord\nWHERE meas_name = 'RRU.PrbTotDl' AND ran_ue_id IS NOT NULL\n AND tstamp BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nGROUP BY tstamp, ran_ue_id\nORDER BY tstamp",
     "rawQueryText": "SELECT\n   tstamp AS \"time\",\n   'UE ' || ran_ue_id AS metric,\n   AVG(measure_value) AS value\nFROM KPM_MeasRecord\nWHERE meas_name = 'RRU.PrbTotDl' AND ran_ue_id IS NOT NULL\n AND tstamp BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nGROUP BY tstamp, ran_ue_id\nORDER BY tstamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "RRU.PrbTotUl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT\n   tstamp AS \"time\",\n   'UE ' || ran_ue_id AS metric,\n   AVG(measure_value) AS value\nFROM KPM_MeasRecord\nWHERE meas_name = 'RRU.PrbTotUl' AND ran_ue_id IS NOT NULL\n AND tstamp BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nGROUP BY tstamp, ran_ue_id\nORDER BY tstamp",
     "rawQueryText": "SELECT\n   tstamp AS \"time\",\n   'UE ' || ran_ue_id AS metric,\n   AVG(measure_value) AS value\nFROM KPM_MeasRecord\nWHERE meas_name = 'RRU.PrbTotUl' AND ran_ue_id IS NOT NULL\n AND tstamp BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nGROUP BY tstamp, ran_ue_id\nORDER BY tstamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "DRB.RlcSduDelayDl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "queryText": "SELECT\n    tstamp AS \"time\",\n    'UE ' || ran_ue_id AS metric,\n    AVG(measure_value) AS value\nFROM KPM_MeasRecord\nWHERE meas_name = 'DRB.RlcSduDelayDl' AND ran_ue_id IS NOT NULL\n AND tstamp BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nGROUP BY tstamp, ran_ue_id\nORDER BY tstamp",
     "rawQueryText": "SELECT\n    tstamp AS \"time\",\n    'UE ' || ran_ue_id AS metric,\n    AVG(measure_value) AS value\nFROM KPM_MeasRecord\nWHERE meas_name = 'DRB.RlcSduDelayDl' AND ran_ue_id IS NOT NULL\n AND tstamp BETWEEN $__unixEpochFrom() AND $__unixEpochTo()\nGROUP BY tstamp, ran_ue_id\nORDER BY tstamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}