#/*
# * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
# * contributor license agreements.  See the NOTICE file distributed with
# * this work for additional information regarding copyright ownership.
# * The OpenAirInterface Software Alliance licenses this file to You under
# * the OAI Public License, Version 1.1  (the "License"); you may not use this file
# * except in compliance with the License.
# * You may obtain a copy of the License at
# *
# *      http://www.openairinterface.org/?page_id=698
# *
# * Unless required by applicable law or agreed to in writing, software
# * distributed under the License is distributed on an "AS IS" BASIS,
# * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# * See the License for the specific language governing permissions and
# * limitations under the License.
# *-------------------------------------------------------------------------------
# * For more information about the OpenAirInterface (OAI) Software Alliance:
# *      contact@openairinterface.org
# */
#
#---------------------------------------------------------------------
#
# Dockerfile for the Open-Air-Interface FlexRIC service
#   Valid for Ubuntu-22.04 (jammy)
#
#---------------------------------------------------------------------
# BUILDER IMAGE
#---------------------------------------------------------------------
ARG BASE_IMAGE=ubuntu:jammy

FROM $BASE_IMAGE AS oai-flexric-base
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris

#install developers pkg/repo
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
       build-essential \
       libsctp-dev \
       git \
       wget \
       tar \
       m4 \
       automake \
       libtool \
       python3 \
       cmake \
       cmake-curses-gui \
       bison \
       flex \
       gdb \
       libpcre2-dev \
       python3-dev \
       python3-pip \
       gcc-12 \
       g++-12 \
       mold \
       ninja-build && \
    apt-get clean

RUN git clone https://github.com/swig/swig.git && \
    cd swig && \
    git checkout release-4.1 && \
    ./autogen.sh && \
    ./configure --prefix=/usr/ && \
    make -j8 && \
    make install && \
    ldconfig

FROM oai-flexric-base AS oai-flexric-builder
ARG E2AP_VERSION=E2AP_V3
ARG KPM_VERSION=KPM_V3_00

WORKDIR /flexric

RUN git clone https://gitlab.eurecom.fr/mosaic5g/flexric /flexric
WORKDIR /flexric
RUN git checkout dev 

COPY ./flexric .
RUN mkdir build && \
    cd build && \
    cmake -GNinja -DCMAKE_BUILD_TYPE=Release \
          -DE2AP_VERSION=$E2AP_VERSION \
          -DKPM_VERSION=$KPM_VERSION \
          -DCMAKE_C_FLAGS_RELEASE="-O3" \
          -DCMAKE_CXX_FLAGS_RELEASE="-O3" \
          -DCMAKE_C_COMPILER=gcc-12 \
          -DCMAKE_CXX_COMPILER=g++-12 .. && \
    ninja && \
    ninja install && \
    echo "--- Check shared objects dependencies for executable nearRT-RIC ---" && \
    ldd /flexric/build/examples/ric/nearRT-RIC && \
    echo "--- Check shared objects dependencies for xApp shared library ---" && \
    ldd /flexric/build/src/xApp/libe42_xapp_shared.so

#---------------------------------------------------------------------
# TARGET IMAGE
#---------------------------------------------------------------------

FROM $BASE_IMAGE AS oai-flexric
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Paris
ENV XAPP_DURATION=-1

#install pkg/repo needed to run
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get upgrade --yes && \
    DEBIAN_FRONTEND=noninteractive apt-get install --yes \
       psmisc \
       gpg \
       wget \
       libsctp1 \
       python3 \
       python3-pip
       ## python3-pip && \
       ## apt-get autoremove -y && \
       ## apt-get autoclean -y

WORKDIR /

COPY --from=oai-flexric-builder \
    /usr/local/lib/flexric/libmac_sm.so \
    /usr/local/lib/flexric/libkpm_sm.so \
    /usr/local/lib/flexric/librlc_sm.so \
    /usr/local/lib/flexric/libslice_sm.so \
    /usr/local/lib/flexric/libtc_sm.so \
    /usr/local/lib/flexric/libgtp_sm.so \
    /usr/local/lib/flexric/libpdcp_sm.so \
    /usr/local/lib/flexric/librc_sm.so \
    /usr/local/lib/flexric/

COPY --from=oai-flexric-builder \
    /flexric/build/src/xApp/libe42_xapp_shared.so \
    /flexric/build/src/xApp/

COPY --from=oai-flexric-builder \
    /flexric/build/examples/ric/nearRT-RIC /usr/local/bin/nearRT-RIC

## Copy xApps
COPY --from=oai-flexric-builder \
    /flexric/build/examples/xApp /usr/local/flexric/xApp

RUN ldconfig && \
    echo "--- Check shared objects dependencies for executable nearRT-RIC ---" && \
    ldd /usr/local/bin/nearRT-RIC && \
    echo "--- Check shared objects dependencies for xApp shared library ---" && \
    ldd /flexric/build/src/xApp/libe42_xapp_shared.so && \
    echo "--- Check shared objects dependencies for flexric shared libraries ---" && \
    ldd /usr/local/lib/flexric/*.so

## E2
EXPOSE 36421/sctp
## E42
EXPOSE 36422/sctp

RUN apt update --fix-missing && apt upgrade -y && \
    apt-get install apt-utils net-tools iputils-ping -y && \
    apt-get install bash bash-completion ethtool -y && \
    apt-get  install iproute2 busybox-static iperf -y && \
    apt-get  install stress-ng curl tcpdump netcat-openbsd -y && \
    apt-get install  libssl-dev libsctp-dev -y && \
    apt-get autoremove -y && \
    apt-get autoclean -y && \
    rm -rf /var/lib/apt/lists/*

COPY ./dockerfiles/volumes/flexric_gnb.conf /usr/local/etc/flexric/flexric_gnb.conf
COPY ./dockerfiles/volumes/flexric_cu.conf /usr/local/etc/flexric/flexric_cu.conf
COPY ./dockerfiles/volumes/flexric_du.conf /usr/local/etc/flexric/flexric_du.conf
COPY ./dockerfiles/volumes/flexric_cucp.conf /usr/local/etc/flexric/flexric_cucp.conf
COPY ./dockerfiles/volumes/flexric_cuup.conf /usr/local/etc/flexric/flexric_cuup.conf
COPY ./dockerfiles/volumes/ric.conf /usr/local/etc/flexric/ric.conf
COPY ./dockerfiles/volumes/ric.conf /usr/local/etc/flexric/flexric.conf

WORKDIR /flexric/build

ENTRYPOINT [""]
CMD ["sh", "-C". "sleep infinity"]
#CMD ["stdbuf", "-o0", "nearRT-RIC"]
