# steering-scenario-primary:
#   routeToLocs:
#     - dnai: access
#     - dnai: internet-primary
# steering-scenario-secondary:
#   routeToLocs:
#     - dnai: access
#     - dnai: internet-secondary
# steering-scenario-embb:
#   routeToLocs:
#     - dnai: access
#     - dnai: internet-co
# steering-scenario-urllc:
#   routeToLocs:
#     - dnai: access
#     - dnai: internet-edge
# steering-scenario-miot:
#   routeToLocs:
#     - dnai: access
#     - dnai: internet-primary

steering-scenario-primary:
  routeToLocs: []
steering-scenario-secondary:
  routeToLocs: []
steering-scenario-embb:
  routeToLocs: []
steering-scenario-urllc:
  routeToLocs: []
steering-scenario-miot:
  routeToLocs: []