/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `TrafficControlDataODB`;

CREATE TABLE `TrafficControlDataODB` (
  `TcId` VARCHAR(128) NOT NULL PRIMARY KEY,
  `FlowStatus` TEXT NOT NULL,
  `FlowStatusIsSet` TINYINT(1) NOT NULL,
  `RedirectInfo` TEXT NOT NULL,
  `RedirectInfoIsSet` TINYINT(1) NOT NULL,
  `AddRedirectInfo` TEXT NOT NULL,
  `AddRedirectInfoIsSet` TINYINT(1) NOT NULL,
  `MuteNotif` TINYINT(1) NOT NULL,
  `MuteNotifIsSet` TINYINT(1) NOT NULL,
  `TrafficSteeringPolIdDl` TEXT NOT NULL,
  `TrafficSteeringPolIdDlIsSet` TINYINT(1) NOT NULL,
  `TrafficSteeringPolIdUl` TEXT NOT NULL,
  `TrafficSteeringPolIdUlIsSet` TINYINT(1) NOT NULL,
  `RouteToLocs` TEXT NOT NULL,
  `RouteToLocsIsSet` TINYINT(1) NOT NULL,
  `TraffCorreInd` TINYINT(1) NOT NULL,
  `TraffCorreIndIsSet` TINYINT(1) NOT NULL,
  `UpPathChgEvent` TEXT NOT NULL,
  `UpPathChgEventIsSet` TINYINT(1) NOT NULL,
  `SteerFun` TEXT NOT NULL,
  `SteerFunIsSet` TINYINT(1) NOT NULL,
  `SteerModeDl` TEXT NOT NULL,
  `SteerModeDlIsSet` TINYINT(1) NOT NULL,
  `SteerModeUl` TEXT NOT NULL,
  `SteerModeUlIsSet` TINYINT(1) NOT NULL,
  `MulAccCtrl` TEXT NOT NULL,
  `MulAccCtrlIsSet` TINYINT(1) NOT NULL)
 ENGINE=InnoDB;

 INSERT INTO `TrafficControlDataODB` (
  `TcId`,`FlowStatus`,`FlowStatusIsSet`,`RedirectInfo`,`RedirectInfoIsSet`,
  `AddRedirectInfo`,`AddRedirectInfoIsSet`,`MuteNotif`,`MuteNotifIsSet`,
  `TrafficSteeringPolIdDl`,`TrafficSteeringPolIdDlIsSet`,
  `TrafficSteeringPolIdUl`,`TrafficSteeringPolIdUlIsSet`,
  `RouteToLocs`,`RouteToLocsIsSet`,`TraffCorreInd`,`TraffCorreIndIsSet`,
  `UpPathChgEvent`,`UpPathChgEventIsSet`,`SteerFun`,`SteerFunIsSet`,
  `SteerModeDl`,`SteerModeDlIsSet`,`SteerModeUl`,`SteerModeUlIsSet`,
  `MulAccCtrl`,`MulAccCtrlIsSet`
) VALUES
('steering-scenario-embb', '',0,'',0,'',0,0,0,'',0,'',0,'[{"dnai":"internet-embb"}]', 1,0,0,'',0,'',0,'',0,'',0,'',0),
('steering-scenario-urllc','',0,'',0,'',0,0,0,'',0,'',0,'[{"dnai":"internet-urllc"}]',1,0,0,'',0,'',0,'',0,'',0,'',0),
('steering-scenario-miot', '',0,'',0,'',0,0,0,'',0,'',0,'[{"dnai":"internet-miot"}]', 1,0,0,'',0,'',0,'',0,'',0,'',0);