uicc0 = {
  imsi = "208950000000130";#"208950000000129";
  key = "0C0A34601D4F07677303652C0462535B";
  opc= "63bfa50ee6523365ff14c1f45f88737d";
  pdu_sessions = (
    {
      id = 1;
      type = "IPV4";
      dnn = "oai.2";
      nssai_sst = 1;
      nssai_sd = "000002";
    }
  );
}

#thread-pool = "-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1"
#thread-pool = "2,2,2,2,2,2,2,2,2,2,2,2"
#/* configuration for channel modelisation */
#/* To be included in main config file when */
#/* channel modelisation is used (rfsimulator with chanmod options enabled) */

log_config :
{
  global_log_level                      ="debug";
  hw_log_level                          ="debug";
  phy_log_level                         ="debug";
  mac_log_level                         ="debug";
  rlc_log_level                         ="debug";
  pdcp_log_level                        ="debug";
  rrc_log_level                         ="debug";
  f1ap_log_level                         ="debug";
  ngap_log_level                         ="debug";
};


MACRLCs = (
        {
        num_cc = 1;
        tr_n_preference = "nfapi";
        remote_n_address = "192.168.80.163 "; //Proxy IP
        local_n_address  = "192.168.80.170 ";
        local_n_portc    = 3612;
        remote_n_portc   = 3611;
        local_n_portd    = 3612;
        remote_n_portd   = 3611;
        }
);

nfapi = "STANDALONE_PNF"; 
node-number = "2"; 
sa = "true"; 
emulate-l1 = "true";   
r = "106"; 
numerology = "1"; 
C = "3619200000"; 
ssb = "516";      